### PR TITLE
feat(Player): Add support for Proof of Identity tokens

### LINKED ISSUE #674: Allow passing poToken for unblock YouTube restrictions
### Describe your suggestion

Hello,
Could you please add the ability to pass the `poToken`? Here is a JSON example:
```
{
   "videoId":"aaaaaaa",
   "context":{
      "client":{
      },
   "serviceIntegrityDimensions": {
		"poToken": "verylongstring"
	}
}
```

Like it's already possible to do it with visitor_data.

This will allow to "unblock" the YouTube restrictions on a blocked IP where YouTube returns `Sign in to confirm you’re not a bot`.

Thank you

### Other details

https://github.com/iv-org/invidious/issues/4734

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

### LINKED ISSUE #696: <10.1.0> <LOGIN_REQUIRED>
### Steps to reproduce

use getbasicinfo() for any of the youtube video with any of the server location.
result throws "LOGIN_REQUIRED" for any of the youtube videos.
we can't access any youtube video without login

### Failure Logs

```shell
status: "LOGIN_REQUIRED"
```

### Expected behavior

need it to be worked without account login

### Current behavior

throwing "LOGIN_REQUIRED" for any of the youtube videos

### Version

Default

### Anything else?

_No response_

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

### PR DESCRIPTION
**Pull request by unixfox**
This PR adds the ability to configure po_token.

Fixes #674
Fixes #696

### CODE REVIEW

**Comment by unixfox** [comment]
Maybe I should provide some instructions on how to generate that famous potoken? Like linking to https://github.com/iv-org/youtube-trusted-session-generator

But I have no idea where you would want that? The "option" section already contains a lot of things: https://github.com/LuanRT/YouTube.js?tab=readme-ov-file#options

**Comment by LuanRT** [comment]
Usually, we add docs for things like this [here](https://github.com/LuanRT/YouTube.js/tree/main/docs). Just a link to invidious' po token generator in the readme would be more than enough.

**Comment by unixfox** [comment]
@LuanRT I have added a link to invidious youtube-trusted-session-generator in the same "options" section in the README

**Comment by MaksymPylypenko** [comment]
Tried copying them from the browser:
```
po_token:"MnTFOHrx2ZbFMcUAqVR2f_PRzEIP5qfkbb-Kk6c5jcMbYqeGVSsbpkoEkfUlKN_NGbWnkUEFi-f3EFtq9mozm_mE_ZQLq2ljjVH3OjP2FZDBVEmheqvHTrDnN2ZmK6O9sdCeGi8BAixnidGaZTn0H_Do4K7N-g==",
visitor_data:"Cgs0T1RXZU11WVRDNCjmncq1BjIKCgJDQRIEGgAgJg%3D%3D"
```
Playback requests are still failing with 403
https://www.youtube.com/watch?v=ocDlOD1Hw9k

**Comment by LuanRT** [comment]
@MaksymPylypenko 
You'll have to add it to the videoplayback requests as (`pot` query param), it won't work properly otherwise.

**Review by LuanRT — APPROVED** [review]

**Comment by LuanRT** [comment]
Looks good and works like a charm. Merging.
@unixfox Thank you!

**Pull request merged**
