### PR TITLE
feat(Kids): Add `blockChannel` command to easily block channels

### PR DESCRIPTION
**Pull request by rsandbach**
Added new command and classes to support the Report / Block channel for kids

image

Small change to ToggleButton to allow parsing when there is now defaultIcon defined.

### CODE REVIEW

**Comment by rsandbach** [comment]
This would be a start to #422.

**Comment by absidue** [comment]
Probably better to put the kids only block channel in `src/core/clients/Kids.ts` instead of the interaction manager, as they presumably can't be used for YouTube or YouTube Music?

Please place your new kids only parser classes in the `src/parser/classes/ytkids` instead of `src/parser/classes/channels`.

**Comment by rsandbach** [comment]
I went back and forth on this. My initial implementation was under Kids, but these particular actions/UI elements are only available within the YouTube web client when logged into an account that curates content for supervised accounts/kids profiles.

**Comment by LuanRT** [comment]
Just skimming through the code and it looks good. Will do a proper review tomorrow or Tuesday.

**Review by LuanRT — APPROVED** [review]

**Comment by ChipWolf** [comment]
> Probably better to put the kids only block channel in `src/core/clients/Kids.ts` instead of the interaction manager, as they presumably can't be used for YouTube or YouTube Music?
> 
> Please place your new kids only parser classes in the `src/parser/classes/ytkids` instead of `src/parser/classes/channels`.

This is nothing to do with ytkids. This is for supervised child accounts that are set to 'Explore', giving them access to yt proper.

**Pull request merged**
