### PR TITLE
fix: missing thirdParty? property in Context

### PR DESCRIPTION
**Pull request by itsmenewbie03**
# Pull Request Template

## Description

implemented the suggestion by @unixfox found at https://github.com/LuanRT/YouTube.js/pull/193#issuecomment-1250233418

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by unixfox** [comment]
I think you might want to rebase all the commits.

**Comment by itsmenewbie03** [comment]
> I think you might want to rebase all the commits.

how do I do that? I'm kinda new in trying to contribute in projects. This is the first project I contributed actually.

**Comment by unixfox** [comment]
Something like "git squash all commits", like here: https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together

**Comment by itsmenewbie03** [comment]
gonna fork a new one hahaha

**Pull request closed without merging**
