### PR TITLE
refactor(Parser)!: general refactoring of parsers

### PR DESCRIPTION
**Pull request by Wykerd**
## Description

General refactor of parsers to cleanup the codebase.

## Breaking Changes

- Removes PlaylistAuthor in favor of Author
- Removes NavigatableText in favor of Text
- YT.VideoInfo constructor changed to match those of YTKids and YTMusic

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by LuanRT — APPROVED** [review]

**Comment by Wykerd** [comment]
> You might have to rebase this pull request on top of the main branch so that you don't break #351. This pull request doesn't pass an `Actions` instance to the toDash function, which is needed to generate the DASH manifest for the OTF format streams.

Fixed. Already did a merge, just forgot to update the toDash method of MediaInfo.

**Comment by absidue** [comment]
Thanks for fixing that, also it's probably worth changing the start of the title from `refactor(Parser)` to `refactor(Parser)!` so that it release please marks it this as a breaking change in the changelog. Things like the constructor for Video info changed and the PlaylistAuthor class was removed, as both of those are exported from the library, it's entirely possible that they could be used in user's code, which will break with this change.

**Comment by absidue** [comment]
https://github.com/googleapis/release-please#how-can-i-fix-release-notes alternatively you can add a section like this to the pull request description to override the message that release please uses. That way you could also list the specific things that are breaking changes (tried it in #351 but need to wait for release please to run again before I know if it worked)

**Comment by LuanRT** [comment]
> (tried it in #351 but need to wait for release please to run again before I know if it worked)

Seems like it did.

**Comment by Wykerd** [comment]
I just realized I already did merge NavigatableText and Text for #310 oops

**Comment by absidue** [comment]
> I just realized I already did merge NavigatableText and Text for #310 oops

You can do the commit override stuff after a pull request is merged too. Release-please digs through all pull requests merged since the last release every time it runs (when a commit is pushed to the main branch either directly or by a pull request getting merged)

**Review by LuanRT — APPROVED** [review]

**Pull request merged**
